name: Java CI

on:
  push:
  repository_dispatch:
    types: [shared-dto-build]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.14
      uses: actions/setup-java@v1
      with:
        java-version: 1.14
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -Dmaven.test.skip -s .settings.xml -Dmaven.javadoc.skip -Dossrh_username=${{secrets.ossrh_username}} -Dossrh_password=${{secrets.ossrh_password}} --file pom.xml deploy
    - name: Repository Dispatch App-Base-Server
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: wannagodev1/app-base-server
        event-type: shared-commons-build
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
    - name: Repository Dispatch App-Audit-Server
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: wannagodev1/app-audit-server
        event-type: shared-commons-build
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
    - name: Repository Dispatch App-Authorization-Server
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: wannagodev1/app-authorization-server
        event-type: shared-commons-build
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
    - name: Repository Dispatch App-Frontend-Application
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: wannagodev1/app-frontend-application
        event-type: shared-commons-build
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
    - name: Repository Dispatch App-I18n-Server
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: wannagodev1/app-i18n-server
        event-type: shared-commons-build
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
    - name: Repository Dispatch App-Resource-Server
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: wannagodev1/app-resource-server
        event-type: shared-commons-build
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
    - name: Repository Dispatch Utils-Config-Server
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: wannagodev1/utils-config-server
        event-type: shared-commons-build
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
    - name: Repository Dispatch Utils-Discovery-Server
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: wannagodev1/utils-discovery-server
        event-type: shared-commons-build
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
    - name: Repository Dispatch Utils-Monitoring-Application
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: wannagodev1/utils-monitoring-application
        event-type: shared-commons-build
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'